### ISSUE TITLE
undefined method `proxy' for #<Middleman::Paginate::Extension>

### ISSUE THREAD

**Issue by lcpriest** [cantierecreativo/middleman-paginate#3]
Has this error occurred for anyone else? If I add 

```
activate :pagination
```
to my config.rb it works fine, but as soon as I add

```
paginate dato.articles.select{ |a| a.published }.sort_by(&:published_at), "/blog", "/templates/posts.html"
```

it throws an error.

**Comment by stefanoverna** [comment]
could you please post the complete stack trace and config.rb file?

**Comment by lcpriest** [comment]
```
page '/*.xml', layout: false
page '/*.json', layout: false
page '/*.txt', layout: false

# Reload the browser automatically whenever files change
configure :development do
  activate :livereload
  set :debug_assets, true
end

activate :sprockets
activate :directory_indexes
activate :pry

activate :dato,
  token: '3815fcac7d06851f10dd5bd133ea95ebbb18ff061eb4f701c1',
  base_url: 'https://advocate.ly'

set :url_root, 'https://advocate.ly'

ignore "/templates/*"

activate :pagination

dato.tags.each do |resource|
  articles = dato.articles.select { |a| a.tags.any? { |t| t.id == resource.id } }
  articles = articles.select { |article| article.published }
  paginate articles, "/blog/tags/#{resource.name.parameterize}",
    "/templates/posts.html",
    per_page: 5,
    data: {
      title: "#{resource.name} | Advocately",
      layout: 'blog',
      extra_classes: 'page-blog'
    },
    locals: {
      resource: resource,
    }
end

dato.categories.each do |resource|
  articles = dato.articles.select {|a| a.category.id == resource.id }
  articles = articles.select { |article| article.published }
  paginate articles, "/blog/categories/#{resource.name.parameterize}",
    "/templates/posts.html",
    per_page: 5,
    data: {
      title: "#{resource.name} | Advocately",
      layout: 'blog',
      extra_classes: 'page-blog'
    },
    locals: {
      resource: resource,
    }
end

dato.articles.select { |article| article.published }.each do |post|
  proxy "/blog/#{post.title.parameterize}.html", "/templates/post.html", locals: {
    post: post,
    extra_classes: 'page-post',
    layout: 'blog',
    title: "#{post.title} | Advocately"
  }
end

paginate dato.articles, "/blog",
  "/templates/posts.html",
  per_page: 5,
  data: {
    title: "Blog | Advocately",
    layout: 'blog',
    extra_classes: 'page-blog'
  }


set :css_dir, 'stylesheets'
set :js_dir, 'javascripts'
set :images_dir, 'images'

# Build-specific configuration
configure :build do
  # Minify CSS on build
  activate :minify_css
  # Minify HTML on build
  activate :minify_html
  # Minify Javascript on build
  activate :minify_javascript
end

helpers do
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new
    Redcarpet::Markdown.new(renderer).render(text)
  end

  def image_or_missing(image)
    if image
      yield image
    else
      image_tag "/images/missing-image.png"
    end
  end
end
```

I tracked it down to being v 0.1.3 - but got no further than that as I locked the gem version to 0.1.2.

This is the trace when moving up to 0.1.3.

```
bundler: failed to load command: middleman (/Users/lcp/.rbenv/versions/2.3.1/bin/middleman)
NoMethodError: undefined method `proxy' for #<Middleman::Paginate::Extension:0x007fed4cc349c0>
Did you mean?  proc
  /Users/lcp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-paginate-0.1.3/lib/middleman/paginate/extension.rb:44:in `block (2 levels) in paginate'
  /Users/lcp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-paginate-0.1.3/lib/middleman/paginate/extension.rb:37:in `each'
  /Users/lcp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-paginate-0.1.3/lib/middleman/paginate/extension.rb:37:in `each_with_index'
  /Users/lcp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-paginate-0.1.3/lib/middleman/paginate/extension.rb:37:in `block in paginate'
  /Users/lcp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-paginate-0.1.3/lib/middleman/paginate/extension.rb:34:in `tap'
  /Users/lcp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-paginate-0.1.3/lib/middleman/paginate/extension.rb:34:in `paginate'
  /Users/lcp/Development/advocate/marketing/config.rb:28:in `block in evaluate_configuration!'
  /Users/lcp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dato-0.1.29/lib/dato/local/items_repo.rb:144:in `each'
  /Users/lcp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dato-0.1.29/lib/dato/local/items_repo.rb:144:in `each'
  /Users/lcp/Development/advocate/marketing/config.rb:25:in `evaluate_configuration!'
  /Users/lcp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/application.rb:329:in `instance_eval'
  /Users/lcp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/application.rb:329:in `evaluate_configuration!'
  /Users/lcp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/application.rb:286:in `initialize'
  /Users/lcp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-cli-4.2.0/bin/middleman:49:in `new'
  /Users/lcp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-cli-4.2.0/bin/middleman:49:in `<top (required)>'
  /Users/lcp/.rbenv/versions/2.3.1/bin/middleman:22:in `load'
  /Users/lcp/.rbenv/versions/2.3.1/bin/middleman:22:in `<top (required)>'
```

**Comment by matteoscurati** [comment]
Same error here.

My config.rb:

```
page '/*.xml', layout: false
page '/*.json', layout: false
page '/*.txt', layout: false
page '/redirects', layout: false

set :url_root, 'https://www.macrogeo.global'

ignore '/templates/*'

activate :directory_indexes
activate :pagination

activate :dato,
  token: '952ea96c4d733ed48d05d37a808171291c01d9ebad2ce31a66',
  base_url: 'https://www.macrogeo.global'

#about

about = app.dato_items_repo.about

proxy "/about/index.html", "/templates/about.html", locals: { about: about }

#services

service = app.dato_items_repo.service

proxy "/services/index.html", "/templates/services.html", locals: { service: service }

#authors

all_authors = app.dato_items_repo.article_authors.sort_by(&:last_name)

boss = all_authors.select { |b| b.boss }
boss = boss.sort_by(&:last_name)

authors = all_authors - boss

heads = authors.select { |h| h.heads }
heads = heads.sort_by(&:last_name)

authors = authors - heads

collective = all_authors.select { |c| c.collective }
collective = collective.sort_by(&:last_name)

authors = authors - collective
authors = authors.sort_by(&:last_name)

proxy "/experts/index.html", "/templates/authors.html", locals: { authors: authors, boss: boss, collective: collective, heads: heads }

all_authors.each do |author|
  proxy "/expert/#{author.slug}.html", "/templates/author.html", locals: { author: author }
end

#articles

published_articles = app.dato_items_repo.articles.select { |a| a.published }
published_articles = published_articles.sort_by(&:date).reverse!

#nexus

published_analysis = published_articles.select { |a| a.macrocategory.id == "26439" }

macrocategory_analysis = app.dato_items_repo.macrocategories.detect { |m| m.id == "26439" }

featured_analysis = published_analysis.select { |a| a.featured }

all_analysis = published_analysis - featured_analysis

proxy "/nexus/index.html", "/templates/analysis.html", locals: { macrocategory: macrocategory_analysis, featured_analysis: featured_analysis, analysis: all_analysis }

published_analysis.each do |article|
  proxy "/nexus/#{article.slug}.html", "/templates/article.html", locals: { article: article }
end

# geopolitics

published_geopolitics = published_articles.select { |a| a.macrocategory.id == "26440" }

macrocategory_geopolitics = app.dato_items_repo.macrocategories.detect { |m| m.id == "26440" }

map_geopolitics = published_geopolitics.select { |a| a.map }
map_geopolitics = map_geopolitics[0]

all_geopolitics = published_geopolitics - [map_geopolitics]

paginate all_geopolitics, "/geopolitics", "/templates/geopolitics.html", locals: { macrocategory: macrocategory_geopolitics, map_geopolitics: map_geopolitics }
#proxy "/geopolitics/index.html", "/templates/geopolitics.html", locals: { macrocategory: macrocategory_geopolitics, map_geopolitics: map_geopolitics, geopolitics: all_geopolitics }

published_geopolitics.each do |article|
  proxy "/geopolitics/#{article.slug}.html", "/templates/article.html", locals: { article: article }
end

# macrofinancial

published_macrofinancials = published_articles.select { |a| a.macrocategory.id == "26441" }

macrocategory_macrofinancial = app.dato_items_repo.macrocategories.detect { |m| m.id == "26441" }

proxy "/macro-finance/index.html", "/templates/macrofinancials.html", locals: { macrocategory: macrocategory_macrofinancial, macrofinancials: published_macrofinancials }

published_macrofinancials.each do |article|
  proxy "/macro-finance/#{article.slug}.html", "/templates/article.html", locals: { article: article }
end

# categories

categories = app.dato_items_repo.categories

categories.each do |category|
  proxy "/category/#{category.slug}.html", "/templates/category.html", locals: { category: category, articles: published_articles }
end

# Search
#todo fix article slug

proxy "/search/index.html", "/templates/search.html", locals: { articles: published_articles }

# events

events = app.dato_items_repo.events.sort_by(&:date)

proxy "/events/index.html", "/templates/events.html", locals: { events: events }

#events.each do |event|
  #proxy "/event/#{event.slug}.html", "/templates/event.html", locals: { event: event }
#end

#home

proxy "/index.html", "/templates/index.html", locals: { featured_analysis: featured_analysis, analysis: all_analysis, map_geopolitics: map_geopolitics, geopolitics: all_geopolitics, macrofinancials: published_macrofinancials, events: events }

#profiles

all_profiles = dato.profiles.sort_by(&:position)

all_profiles.each do |profile|
  proxy "/profile/#{profile.slug}.html", "/templates/author.html", ignore: true, locals: { author: profile }
end

# contacts

contact = app.dato_items_repo.contact

proxy "/contacts/index.html", "/templates/contacts.html", locals: { contact: contact }

# Assets
set :css_dir, 'dist/stylesheets'
set :js_dir, 'dist/javascripts'
set :images_dir, 'dist/images'

# External pipeline
activate :external_pipeline,
  name: :gulp,
  command: build? ? 'gulp build --production' : './node_modules/gulp/bin/gulp.js',
  source: "dist",
  latency: 1

# Build-specific configuration
configure :build do
  ignore 'assets/*'
  activate :gzip
  activate :minify_html, remove_intertag_spaces: true
  activate :asset_hash
  activate :relative_assets
  activate :search_engine_sitemap,
    default_priority: 0.5,
    default_change_frequency: 'weekly'
end

after_build do
  File.rename 'build/redirects', 'build/_redirects'
end

#helpers
helpers do
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new
    Redcarpet::Markdown.new(renderer).render(text)
  end

  def name(first_name, last_name)
    "#{first_name} #{last_name}"
  end
end
```

And the trace:

```
bundler: failed to load command: middleman (/Users/matteoscurati/.rbenv/versions/2.3.1/bin/middleman)
NoMethodError: undefined method `proxy' for #<Middleman::Paginate::Extension:0x007ff6c4e1d620>
Did you mean?  proc
  /Users/matteoscurati/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-paginate-0.1.3/lib/middleman/paginate/extension.rb:45:in `block (2 levels) in paginate'
  /Users/matteoscurati/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-paginate-0.1.3/lib/middleman/paginate/extension.rb:37:in `each'
  /Users/matteoscurati/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-paginate-0.1.3/lib/middleman/paginate/extension.rb:37:in `each_with_index'
  /Users/matteoscurati/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-paginate-0.1.3/lib/middleman/paginate/extension.rb:37:in `block in paginate'
  /Users/matteoscurati/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-paginate-0.1.3/lib/middleman/paginate/extension.rb:34:in `tap'
  /Users/matteoscurati/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-paginate-0.1.3/lib/middleman/paginate/extension.rb:34:in `paginate'
  /Users/matteoscurati/work/macrogeo/macrogeo.global/config.rb:89:in `evaluate_configuration!'
  /Users/matteoscurati/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/application.rb:329:in `instance_eval'
  /Users/matteoscurati/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/application.rb:329:in `evaluate_configuration!'
  /Users/matteoscurati/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/application.rb:286:in `initialize'
  /Users/matteoscurati/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-cli-4.2.1/bin/middleman:49:in `new'
  /Users/matteoscurati/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-cli-4.2.1/bin/middleman:49:in `<top (required)>'
  /Users/matteoscurati/.rbenv/versions/2.3.1/bin/middleman:23:in `load'
  /Users/matteoscurati/.rbenv/versions/2.3.1/bin/middleman:23:in `<top (required)>'
```

**Comment by lcpriest** [comment]
@matteoscurati I updated my gem version and it was fixed

**Comment by matteoscurati** [comment]
@lcpriest yes, It's ok with this gem version:

```
middleman-paginate 0.1.4.pre
```

Thx!
