### ISSUE TITLE
ArgumentError: comparison of Fixnum with Middleman::CoreExtensions::Collections::LazyCollectorStep failed

### ISSUE THREAD

**Issue by tai-flywire** [cantierecreativo/middleman-paginate#6]
I'm trying this lib for the first time.  I've never had a working version, so I can't say for sure if I "know" how to do this correctly but anyway, here are the details and you can let me know if it's user error or a true bug.

My guess is that the lib is too old and a newer version of `middleman-core` has broken compatibility.  I'm much more of a Javascript guy than a Ruby guy otherwise I'd fix it for you and submit a pull request.

My Gemfile.lock (TL;DR - `middleman 4.2.1`, `middleman-dato 0.8.1`, `middleman-paginate 0.1.6`)
[Gemfile.lock.txt](https://github.com/cantierecreativo/middleman-paginate/files/2380725/Gemfile.lock.txt)

My config.rb (paginate code is almost at the very end)
```ruby
require "redcarpet"
  
  activate :external_pipeline,
    name: :webpack,
    command: build? ? "npm run build:assets" : "npm run start:assets",
    source: ".tmp/webpack_output",
    latency: 1
  
  activate :dato,
    token: ENV.fetch("DATO_API_TOKEN"), live_reload: true
  
  configure :development do
    activate :livereload
  end
  
  activate :directory_indexes
  activate :pagination
  
  configure :build do
    activate :asset_hash
    activate :minify_html
  end
  activate :i18n, langs: [:en, :es, :fr, :pt, :ko, :ja, :zh], mount_at_root: :en
  
  # Per-page layout changes
  page "/*.xml", layout: false
  page "/*.json", layout: false
  page "/*.txt", layout: false
  
  set :fonts_dir, "stylesheets/fonts"
  
  helpers do
    def list_item(link, list_item_class = "", link_class = "")
      link = link_tag(link, link_class)
      content_tag(:li, link, class: list_item_class)
    end
  
    def link_tag(link, link_class = "", external = false, title = nil)
      return if link.nil?
      url = path(link.slug)
      text = link.text || ""
  
      data_attributes = {}
      if link.tracker_event.present?
        data_attributes = {tracker: true, 'tracker-event': "click", 'tracker-label': link.tracker_event}
      end
  
      attributes = {href: url, class: link_class, title: title ? title : strip_tags(text), data: data_attributes, target:  external ? "_blank" : "_self"}
      if (link.link_id != "")
        attributes[:id] = link.link_id
      end
  
      content_tag(:a, text, attributes)
    end
  
    def button_tag(link, button_class = "", type = "submit")
      return if link.nil?
      text = link.text || ""
  
      data_attributes = {}
      if link.tracker_event.present?
        data_attributes = {tracker: true, 'tracker-event': "click", 'tracker-label': link.tracker_event}
      end
  
      attributes = {class: button_class, title: strip_tags(text), data: data_attributes, type: type}
      if (link.link_id != "")
        attributes[:id] = link.link_id
      end
  
      content_tag(:button, text, attributes)
    end
  
    def modal_form_tag(form, link_class = "", title = nil)
      text = form.link_text || ""
  
      data_attributes = { 'micromodal-trigger': "Modal-form-#{form.id}" }
  
      attributes = {href: 'javascript:void(0)', class: link_class, title: title ? title : strip_tags(text), data: data_attributes, role: 'button'}
  
      content_tag(:a, text, attributes)
    end
  
    def strip_tags(text)
      text.gsub(/(\<.+\>)/, "")
    end
  
    def badge(text)
      content_tag(:span, text, class: "Badge")
    end
  
    def language_selector(options = {})
      list_item_class = options[:list_item_class]
      link_class = options[:link_class]
      trigger_class = options[:trigger_class]
      menu_class = options[:menu_class]
      wrapper_class = options[:wrapper_class]
      links = Array.new
      current_locale = ""
  
      dato.locales.each do |locale|
        if locale.slug != I18n.locale.to_s
          link = content_tag(:a, locale.native, {href: path(current_page.url, lang: locale.slug), class: link_class})
          links.push(content_tag(:li, link, class: list_item_class))
        else
          current_locale = locale
        end
      end
  
      list_items = content_tag(:ul, links.join("\n"), class: menu_class)
      current_locale_link = content_tag(:a, current_locale.native, {href: path(current_page.url, lang: current_locale.slug), class: trigger_class})
  
      content_tag(:div, current_locale_link + list_items, class: wrapper_class, role: "menu")
    end
  
    def language_dropdown()
      available_langs = Array.new
      current_locale = ""
  
      dato.locales.each do |locale|
        if locale.slug != I18n.locale.to_s
          available_langs.push(locale)
        else
          current_locale = locale
        end
      end
  
      require "json"
      sexy = dato.locales.to_json.to_s
  
      return {:current_locale => current_locale, :available_langs => available_langs, :sexy => sexy}
    end
  
    def path(url, options = {})
      lang = options[:lang] || I18n.locale.to_s
  
      return site_url if clean_from_i18n(url) == "/" or clean_from_i18n(url) == "" and lang.to_s == "en"
      return url if url.scan(/mailto:/).any?
      return url if url.scan(/tel:/).any?
      return url if url.scan(/skype/).any?
      return url if url.scan(/https?:\/\/[\S]+/).any?
      return url if url.count("#") > 0
  
      if lang.to_s == "en"
        prefix = ""
      else
        prefix = trailing_slash("#{lang}")
      end
  
      (site_url + prefix + clean_from_i18n(url)).chomp("/")
    end
  
    def trailing_slash(slug)
      if (slug[-1] != "/")
        slug += "/"
      end
      slug
    end
  
    # removes an i18n lang code from url if its present
    def clean_from_i18n(url)
      parts = url.split("/").select { |p| p && p.size > 0 }
      parts.shift if langs.map(&:to_s).include?(parts[0])
  
      parts.join("/")
    end
  
    def img(image, width = false, height = false, img_class = "", alt = "", title = "")
      alt_attribute = image.alt.present? ? image.alt : alt
      title_attribute = image.title.present? ? image.title : title
  
      tag :img,
        src: "#{image.url}?w=#{width}&auto=compress",
        alt: alt_attribute,
        title: title_attribute,
        class: "lazyload #{img_class}",
        width: width,
        height: height
    end
  
    def retina_image(image, width, height, css_class = "", alt = "", title = "")
      alt_attribute = image.alt.present? ? image.alt : alt
      title_attribute = image.title.present? ? image.title : title
      tag :img,
        src: "#{image.url}?w=#{width}&auto=compress",
        srcset: "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==",
        alt: alt_attribute,
        title: title_attribute,
        class: "lazyload #{css_class}",
        width: width,
        height: height,
        data: {
          sizes: "auto",
          srcset: "#{image.url}?w=#{width}&auto=compress&dpr=1 1x,
                  #{image.url}?w=#{width}&auto=compress&dpr=2 2x,
                  #{image.url}?w=#{width}&auto=compress&dpr=3 3x",
        }
    end
  
    def module_background_color(data)
      return if not data.config.present? or not data.config.background_color
      config = data.config
  
      background_color = config.background_color ? config.background_color.hex : "#fff"
      "style='background-color: #{background_color}'"
    end
  
    def module_text_align(data)
      return if not data.config.present? or not data.config.text_align
      config = data.config
  
      text_align = config.text_align ? config.text_align : "initial"
      "style='text-align: #{text_align}'"
    end
  
  
    def module_config_styles(data)
      return if not data.config.present? or not data.config.text_align
      config = data.config
  
      background_color = "background-color: #{config.background_color ? config.background_color.hex : "#fff"};"
      text_align = "text-align: #{config.text_align ? config.text_align : "initial"};"
      "style='#{background_color}#{text_align}'"
    end
  
    def module_image_align(data, left_class = "float-left", right_class = "float-right")
      data.config.present? and data.config.image_align ? right_class : left_class
    end
  
    def module_padding_top(data)
      return if not data.config or not data.config.remove_top_space
      "paddingTop-0"
    end
  
    def module_padding_bottom(data)
      return if not data.config or not data.config.remove_bottom_space
      "paddingBottom-0"
    end
  
    def module_border_top(data)
      return if not data.config or not data.config.border_top
      "borderTop-gray"
    end
  
    def module_border_bottom(data)
      return if not data.config or not data.config.border_bottom
      "borderBottom-gray"
    end
  
    def module_classes(data)
      "#{module_padding_top(data)} #{module_padding_bottom(data)} #{module_border_top(data)}  #{module_border_bottom(data)} "
    end
  
    def paragraph_styles(data)
      if defined? data.bkgr_color
        styles = Hash[
          "Primary" => "Paragraph--primary",
          "Forced" => "Paragraph--forced",
          "Inverted" => "Paragraph--inverted",
          "Neutral" => "Paragraph--neutral"]
  
        styles[data.bkgr_color]
      end
    end
  
    def markdown(text)
      return if text.nil?
      renderer = Redcarpet::Render::HTML.new
      Redcarpet::Markdown.new(renderer).render(text)
    end
  
    def assets_url
      if ENV.key?("ASSETS_URL")
        trailing_slash(ENV["ASSETS_URL"])
      else
        "/"
      end
    end
  
    def site_url
      if ENV.key?("SITE_URL")
        trailing_slash(ENV["SITE_URL"])
      else
        "/"
      end
    end
  
    def javascript_url(file)
      assets_url + trailing_slash("javascripts") + file
    end
  
    def stylesheet_url(file)
      assets_url + trailing_slash("stylesheets") + file
    end
  
    def image_url(file)
      assets_url + trailing_slash("images") + file
    end
  
    def html_to_json(html)
      html.gsub(/>\s*/, ">").gsub(/\s*</, "<").to_json
    end
  
    def locales_array(separator = "_")
      {
        en: "en#{separator}US",
        es: "es#{separator}ES",
        fr: "fr#{separator}FR",
        pt: "pt#{separator}PT",
        zh: "zh#{separator}CN",
        ko: "ko#{separator}KR",
        ja: "ja#{separator}JP",
      }
    end
  
    def language_with_locale(separator = "_")
      locales_array(separator)[I18n.locale]
    end
  
    def production?
      ENV.key?("ENVIRONMENT") && ENV["ENVIRONMENT"] == "production"
    end
  
    def support_slug
      "support"
    end
  
    def support_url
      path("support")
    end
  
    def support_entry_url(entry)
      path("#{support_slug}/#{entry.category.slug}/#{entry.slug}")
    end
  
    def support_category_url(category)
      path("#{support_slug}/#{category.slug}")
    end
  
    def support_search_url
      path("#{support_slug}/search/") + "/"
    end
  
    def news_url
      path(dato.news_page.slug)
    end
  
    def news_entry_url(entry)
      path("#{news_url}/#{entry.category.slug}/#{entry.slug}")
    end
  
    def news_category_url(category)
      path("#{news_url}/#{category.slug}")
    end
  
    def news_per_page
      8
    end
  
    def canonical_url
      tag(:link, {rel: "canonical", href: path(current_page.url, lang: "en")})
    end
  
    def alternate_urls
      locales = locales_array("-")
      alternates = []
  
      locales.each do |locale|
        alternates.push(tag(:link, {rel: "alternate", href: path(current_page.url, lang: locale[0]), hreflang: locale[1]}))
      end
  
      alternates.join("")
    end
  
    def meta_robots(data)
      index_tag = tag(:meta, {name: "robots", content: "index"})
      no_index_tag = tag(:meta, {name: "robots", content: "noindex"})
  
      return no_index_tag if not production?
      return no_index_tag if data.respond_to?(:seo_advanced) && data.seo_advanced.respond_to?(:no_index_page) && data.seo_advanced.no_index_page == true
    end
  
    def head(data)
      "#{meta_robots(data)}#{dato_meta_tags(data)}"
    end
  
    def get_video_offset(dimensions, ratio)
      width = dimensions.split('x')[0].to_i
      height = dimensions.split('x')[1].to_i
      ratio = ratio.to_f
  
      return "%5.2f" % ((width / ratio - height) / width * 100)
    end
  
    def section_id(data)
      return if not data.config or not data.config.section_id
  
      return "id=\"#{data.config.section_id}\""
    end
  end
  
  dato.tap do |dato|
    dato.available_locales.each do |locale|
      I18n.with_locale(locale) do
        locale_slug = locale != :en ? "/#{locale}" : ""
  
        # corporate pages
        dato.narrative_pages.each do |page|
          slug = page.slug
          proxy(
            "#{locale_slug}/#{page.slug}/index.html",
            "/templates/narrative.html",
            locals: {template_data: page, pageHeaderType: "withImage"},
            locale: locale,
          )
        end
  
        # landing pages
        dato.landing_pages.each do |page|
          slug = page.slug
          proxy(
            "#{locale_slug}/#{page.slug}/index.html",
            "/templates/landing-page.html",
            locals: {template_data: page},
            locale: locale,
          )
        end
  
        # corporate pages
        dato.corporate_pages.each do |page|
          slug = page.slug
          proxy(
            "#{locale_slug}/#{page.slug}/index.html",
            "/templates/corporate.html",
            locals: {template_data: page},
            locale: locale,
          )
        end
  
        # legal pages
        dato.legal_pages.each do |page|
          slug = page.slug
          proxy(
            "#{locale_slug}/#{page.slug}/index.html",
            "/templates/legal.html",
            locals: {template_data: page, has_index: false},
            locale: locale,
          )
        end
  
        # flyforum pages
        dato.flyforum_pages.each do |page|
          slug = page.slug
          proxy(
            "#{locale_slug}/#{page.slug}/index.html",
            "/templates/flyforum.html",
            locals: {template_data: page},
            locale: locale,
          )
        end
  
        # support entries
        dato.support_entries.each do |page|
          slug = page.slug
          proxy(
            "#{locale_slug}/support/#{page.category.slug}/#{page.slug}/index.html",
            "/templates/support-entry.html",
            locals: {template_data: page},
            locale: locale,
          )
        end
  
        # support categories
        dato.support_categories.each do |page|
          slug = page.slug
          proxy(
            "#{locale_slug}/support/#{page.slug}/index.html",
            "/templates/support-taxonomy.html",
            locals: {
              template_data: page,
              taxonomy: "category",
            },
            locale: locale,
          )
        end
  
        # support countries
        dato.support_countries.each do |page|
          slug = page.slug
          proxy(
            "#{locale_slug}/support/#{page.slug}/index.html",
            "/templates/support-taxonomy.html",
            locals: {
              template_data: page,
              taxonomy: "country_category",
            },
            locale: locale,
          )
        end
  
        # news index page
        news_slug = dato.news_page.slug
        proxy(
          "#{locale_slug}/#{news_slug}/index.html",
          "/templates/news-index.html",
          locals: {template_data: dato.news_page},
          locale: locale,
        )
  
        # news entries
        dato.news_entries.each do |page|
          slug = page.slug
          proxy(
            "#{locale_slug}/#{news_slug}/#{page.category.slug}/#{page.slug}/index.html",
            "/templates/news-entry.html",
            locals: {template_data: page},
            locale: locale,
          )
        end
  
        # news categories
        dato.news_categories.each do |page|
          slug = page.slug
          proxy(
            "#{locale_slug}/#{news_slug}/#{page.slug}/index.html",
            "/templates/news-category.html",
            locals: {template_data: page},
            locale: locale,
          )
        end
      end
    end
  end
  
  paginate dato.press_releases, "/press", "/templates/press-releases.html", suffix: "/page/:num/index", per_page: 2
  
  ignore "templates/narrative.html.erb"
  ignore "templates/landing-page.html.erb"
  ignore "templates/modular.html.erb"
  ignore "templates/corporate.html.erb"
  ignore "templates/legal.html.erb"
  ignore "templates/flyforum.html.erb"
  ignore "templates/press-releases.html.erb"
  
  ignore "templates/support-entry.html.erb"
  ignore "templates/support-taxonomy.html.erb"
  
  ignore "templates/news-index.html.erb"
  ignore "templates/news-entry.html.erb"
  ignore "templates/news-category.html.erb"

```

And my template press-releases.html (problem code is in the pager, line 29):
```html
<% template_data = dato.press_releases_index %>
<% content_for(:body_class) do %>PageSecondary <% if defined?(template_data.page_config) %><%= template_data.page_config.page_class %><% end %><% end %>

<% content_for(:head) do %>
  <%= head(template_data) %>
<% end %>

<article class="Wrapper">
  <header class="PageTitle">
    <h1 class="PageSecondary-Title"><%= template_data.title %></h1>
    <div class="PageSecondary-Description">
      <% if template_data.description %>
      <div><%= markdown(template_data.description) %></div>
      <% end %>
    </div>
  </header>

  <div class="LegalPage">
    <div class="HTMLContent">
      <% items.each do |release| %>
      <section class="PressRelease">
        <h3 class="PressRelease-Title"><%= release.title %></h3>
        <small><%= release.date %></small>
        <div class="PressRelease-Abstract">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
      </section>
      <% end %>
      <% if pager.next_page %>
        <%= content_tag(:a, 'next', nil, href: pager.page_path(pager.next_page)) %>
      <% end %>
    </div>
  </div>
</article>
```

And this is my trace:
```
/Users/tai.nguyen/.rvm/gems/ruby-2.3.3/gems/middleman-paginate-0.1.6/lib/middleman/paginate/extension.rb:30: warning: Bad return value for #coerce, called by numerical comparison operators.
/Users/tai.nguyen/.rvm/gems/ruby-2.3.3/gems/middleman-paginate-0.1.6/lib/middleman/paginate/extension.rb:30: warning: #coerce must return [x, y]. The next release will raise an error for this.
ArgumentError: comparison of Fixnum with Middleman::CoreExtensions::Collections::LazyCollectorStep failed
	/Users/tai.nguyen/.rvm/gems/ruby-2.3.3/gems/middleman-paginate-0.1.6/lib/middleman/paginate/extension.rb:30:in `<'
	/Users/tai.nguyen/.rvm/gems/ruby-2.3.3/gems/middleman-paginate-0.1.6/lib/middleman/paginate/extension.rb:30:in `next_page'
	/Users/tai.nguyen/Documents/GitHub/cms/source/templates/press-releases.html.erb:29:in `block in singleton class'
	/Users/tai.nguyen/Documents/GitHub/cms/source/templates/press-releases.html.erb:-10:in `instance_eval'
	/Users/tai.nguyen/Documents/GitHub/cms/source/templates/press-releases.html.erb:-10:in `singleton class'
	/Users/tai.nguyen/Documents/GitHub/cms/source/templates/press-releases.html.erb:-13:in `__tilt_70255422841320'
...
```

**Comment by tai-flywire** [comment]
Apparently, it was just a problem with me not putting the paginate command inside my dato.tap block.
